name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 18.14.0

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

  upload:
    needs: build
    uses: ./.github/workflows/upload_build.yml
