name: Deploy code prod
on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    uses: shmarlya/bicep-playground/.github/workflows/build.yml@main
  download_build:
    needs: [build]
    uses: ./.github/workflows/download_build.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [download_build]
    steps:
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.APP_SERVICE_NAME_PROD }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PROD }}
          package: .
