name: Build and deploy code
on:
  workflow_dispatch:

jobs:
  build_and_deploy_prod:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy_code_prod.yml
  build_and_deploy_dev:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy_code_dev.yml
