name: Deploy infrastructure
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true

      - name: log values
        run: echo "$ORG_NAME $BILLING_ACCOUNT_NAME  this is $WEBAPP_NAME"

      - name: Deploy Bicep file
        uses: azure/arm-deploy@v2
        with:
          deploymentName: 'deployInfra'
          scope: 'tenant'
          region: ${{vars.LOCATION}}
          template: .deploy/main.bicep
          parameters: .deploy/main.bicepparam orgName=${{vars.ORG_NAME}} projectName=${{vars.WEBAPP_NAME}} location=${{vars.LOCATION}} billingAccountName=${{vars.BILLING_ACCOUNT_NAME}} billingProfileName=${{vars.BILLING_PROFILE_NAME}} invoiceSectionName=${{vars.INVOICE_SECTION_NAME}} STRIPE_SECRET=${{vars.STRIPE_SECRET}} STRIPE_WEBHOOK_SECRET=${{vars.STRIPE_WEBHOOK_SECRET}}
          failOnStdErr: true
